---
- name: Update Ubuntu and Install Nginx
  hosts: losh_servers
  become: yes

  vars:
    losh_version: "v0.1.1"
    losh_binary_url: "https://github.com/AntonyBaasan/losh/releases/download/{{ losh_version }}/losh-server-linux-amd64"
    losh_binary_path: "/usr/local/bin/losh"

  tasks:

    - name: Update apt cache and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP and HTTPS traffic in UFW (firewall)
      ufw:
        rule: allow
        name: 'Nginx Full'

    - name: Deploy custom index.html landing page
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Create losh user
      user:
        name: loshuser
        system: true
        shell: /usr/sbin/nologin
        create_home: false

    - name: Download losh binary
      get_url:
        url: "{{ losh_binary_url }}"
        dest: "{{ losh_binary_path }}"
        mode: '0755'
    
    # - name: Create data directory
    #   file:
    #     path: /var/lib/losh
    #     state: directory
    #     owner: losh
    #     group: losh
    #     mode: '0755'

    # - name: Create systemd service
    #   copy:
    #     dest: /etc/systemd/system/losh.service
    #     mode: '0644'
    #     content: |
    #       [Unit]
    #       Description=Losh Server
    #       After=network.target

    #       [Service]
    #       Type=simple
    #       User=loshuser
    #       Group=losh
    #       WorkingDirectory=/var/lib/losh
    #       ExecStart=/usr/local/bin/losh
    #       Restart=always
    #       RestartSec=5

    #       [Install]
    #       WantedBy=multi-user.target

    # - name: Reload systemd
    #   systemd:
    #     daemon_reload: true

    # - name: Enable and start losh
    #   systemd:
    #     name: losh
    #     enabled: true
    #     state: started